apiVersion: v1
kind: Service
metadata:
  name: splunk-headless
  namespace: splunk
  labels:
    app: splunk
spec:
  clusterIP: None

  selector:
    app: splunk

  ports:
    - name: web
      port: 8000
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: splunk
  namespace: splunk
  labels:
    app: splunk
spec:
  type: ClusterIP

  selector:
    app: splunk

  ports:
    - name: web
      port: 8000
      targetPort: 8000